#Numpy Exercies for practice

In [1]:
1. # Import NumPy as its abbreviation 'np'

import numpy as np


In [1]:
2. # Create a 1-dimensional NumPy array using np.array()

import numpy as np
a = np.array([1, 3, 5, 7, 9])
print('Our array is:')
print(a)


Our array is:
[1 3 5 7 9]


In [2]:
3. # Create a 2-dimensional NumPy array using np.array()

import numpy as np
a = np.array([[[3,7,5],[8,4,3]]])
print('Our array is:')
print(a)


Our array is:
[[[3 7 5]
  [8 4 3]]]


In [3]:
4. # Create a 3-dimensional Numpy array using np.array()

import numpy as np
a = np.array([[[3,7,5],[8,4,3],[2,4,9]]])
print('Our array is:')
print(a)


Our array is:
[[[3 7 5]
  [8 4 3]
  [2 4 9]]]


In [9]:
5. # Attributes of 1-dimensional array Find the shape, number of dimensions, data type, size and type of each array.

import numpy as np
a = np.array([3,7,5],dtype='int16')
print('Our array is:')
print(a)
print("shape=",a.shape)
print("dimension=",a.ndim)
print("datatype=",a.dtype)
print("size=",a.size)




Our array is:
[3 7 5]
shape= (3,)
dimension= 1
datatype= int16
size= 3


In [10]:
6. # Attributes of 2-dimensional array
import numpy as np
a = np.array([[3,7,5],[8,4,3],[2,4,9]],dtype='int16')
print('Our array is:')
print(a)
print("shape=",a.shape)
print("dimension=",a.ndim)
print("datatype=",a.dtype)
print("size=",a.size)


Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]
shape= (3, 3)
dimension= 2
datatype= int16
size= 9


In [12]:
7. # Attributes of 3-dimensional array
import numpy as np
a = np.array([[[3,7,5],[8,4,3],[2,4,9]]],dtype='int16')
print('Our array is:')
print(a)
print("shape=",a.shape)
print("dimension=",a.ndim)
print("datatype=",a.dtype)
print("size=",a.size)


Our array is:
[[[3 7 5]
  [8 4 3]
  [2 4 9]]]
shape= (1, 3, 3)
dimension= 3
datatype= int16
size= 9


In [6]:
8. # Import pandas and create a DataFrame out of one of the arrays you've created


In [13]:
9. # Create an array of shape (10, 2) with only ones
import numpy as np
x = np.ones([10,2], dtype = int)
print(x)


[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [18]:
10. # Create an array of shape (7, 2, 3) of only zeros
import numpy as np
x = np.zeros([7,2,3], dtype = 'int8')
print(x)


[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [19]:
11. # Create an array within a range of 0 and 100 with step 3
import numpy as np
x = np.arange(0,100,3)
print(x)


[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [84]:
12. # Create a random array with numbers between 0 and 10 of size (7, 2)

b = np.random.randint(0,11,size=(7,2))
print(b)


[[2 6]
 [3 8]
 [2 4]
 [2 6]
 [4 8]
 [6 1]
 [3 8]]


In [85]:
13. # Create a random array of floats between 0 & 1 of shape (3, 5)
x = np.random.rand(3,5)
print(x)



[[0.96563203 0.80839735 0.30461377 0.09767211 0.68423303]
 [0.44015249 0.12203823 0.49517691 0.03438852 0.9093204 ]
 [0.25877998 0.66252228 0.31171108 0.52006802 0.54671028]]


In [82]:
14. # Set the random seed to 42

np.random.seed(42)

In [83]:
15. # Create a random array of numbers between 0 & 10 of size (4, 6) Run the cell above again, what happens?

a=np.random.rand(4,6)
print(a)

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184]]


In [86]:
16. # Create an array of random numbers between 1 & 10 of size (3, 7) and save it to a variable

a=np.random.rand(1,10,size=(3,7))


TypeError: rand() got an unexpected keyword argument 'size'

In [25]:
17. # Find the unique numbers in the array you just created
a = np.array([5,2,6,2,7,5,6,8,2,9])

print('array:')
print(a)
print('\n')

print('Unique values of first array:')
u = np.unique(a)
print(u)


array:
[5 2 6 2 7 5 6 8 2 9]


Unique values of first array:
[2 5 6 7 8 9]


In [26]:
18. # Find the 0'th index of the latest array you created
a = np.array([5,2,6,2,7,5,6,8,2,9])

print('First array:')
print(a)
print('\n')
print(a[0])


First array:
[5 2 6 2 7 5 6 8 2 9]


5


In [39]:
19. # Get the first 2 rows of latest array you created

a = np.array([[[[3,7,5],[8,4,3],[2,4,9]]]],dtype='int16')
print(a[:2,:])



[[[[3 7 5]
   [8 4 3]
   [2 4 9]]]]


In [40]:
20. # Get the first 2 values of the first 2 rows of the latest array

a = np.array([[[[3,7,5],[8,4,3],[2,4,9]]]],dtype='int16')
print(a[:2,:2])

[[[[3 7 5]
   [8 4 3]
   [2 4 9]]]]


In [17]:
21. # Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables


In [42]:
22. # Add the two arrays together

a = np.arange(9, dtype = np.int16).reshape(3,3)
print('First array:')
print(a)
print('\n')

print('Second array:')
b = np.array([10,10,10])
print(b)
print('\n')

print('Add the two arrays:')
print(np.add(a, b))
print('\n')

First array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Second array:
[10 10 10]


Add the two arrays:
[[10 11 12]
 [13 14 15]
 [16 17 18]]




In [43]:
23. # Create another array of ones of shape (5, 3)

x = np.ones([5,3], dtype = int)
print(x)


[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [52]:
24. # Try add the array of ones and the other most recent array together
x = np.ones([3,2], dtype = "int16")
print(x)
a = np.arange(6, dtype = np.int16).reshape(3,2)
print(a)
print(np.add(x,a))

[[1 1]
 [1 1]
 [1 1]]
[[0 1]
 [2 3]
 [4 5]]
[[1 2]
 [3 4]
 [5 6]]


In [54]:
25. # Create another array of ones of shape (3, 5)
x = np.ones([3,5], dtype = "int16")
print(x)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [56]:
26. # Subtract the new array of ones from the other most recent array
a = np.arange(6, dtype = np.int16).reshape(3,2)
b = np.ones([3,2], dtype = "int16")
print(np.subtract(b,a))



[[ 1  0]
 [-1 -2]
 [-3 -4]]


In [58]:
27. # Multiply the ones array with the latest array

b = np.ones([3,2], dtype = "int16")
a = np.array([2])
print(np.multiply(a, b))
print('\n')


[[2 2]
 [2 2]
 [2 2]]




In [64]:
28. # Take the latest array to the power of 2 using '**'

a = np.arange(6, dtype = np.int16).reshape(3,2)
print(a**2)

[[ 0  1]
 [ 4  9]
 [16 25]]


In [65]:
29. # Do the same thing with np.square()

a = np.arange(6, dtype = np.int16).reshape(3,2)
print(np.square(a))

[[ 0  1]
 [ 4  9]
 [16 25]]


In [66]:
30. # Find the mean of the latest array using np.mean()

a = np.arange(6, dtype = np.int16).reshape(3,2)
print(np.mean(a))

2.5


In [68]:
31. # Find the maximum of the latest array using np.max()

a = np.arange(6, dtype = np.int16).reshape(3,2)
print(np.max(a))

5


In [69]:
32. # Find the minimum of the latest array using np.min()

a = np.arange(6, dtype = np.int16).reshape(3,2)
print(np.min(a))

0


In [70]:
33. # Find the standard deviation of the latest array

a = np.arange(6, dtype = np.int16).reshape(3,2)
print(np.std(a))

1.707825127659933


In [71]:
34. # Find the variance of the latest array

a = np.arange(6, dtype = np.int16).reshape(3,2)
print(np.var(a))

2.9166666666666665


In [74]:
35. # Reshape the latest array to (3, 5, 1)

a = np.arange(15, dtype = np.int16).reshape(3,5)
print(a.reshape(3,5,1))

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]]]


In [75]:
36. # Transpose the latest array

a = np.arange(15, dtype = np.int16).reshape(3,5)
print(np.transpose(a))

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [88]:
37. # Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)

a = np.random.randint(0,10,size=(3,3))
b = np.random.randint(0,10,size=(3,2))
print(a)
print('\n')
print(b)


[[8 8 0]
 [8 6 8]
 [7 0 7]]


[[7 2]
 [0 7]
 [2 2]]


In [89]:
38. # Perform a dot product on the two newest arrays you created

a = np.random.randint(0,10,size=(3,3))
b = np.random.randint(0,10,size=(3,2))
print(a)
print('\n')
print(b)
print(np.dot(a,b))

[[0 4 9]
 [6 9 8]
 [6 8 7]]


[[1 0]
 [6 6]
 [7 4]]
[[ 87  60]
 [116  86]
 [103  76]]


In [108]:
39. # Create two arrays of random integers between 0 to 10 both of size (4, 3)
import numpy as np
a = np.random.randint(1,11,size=(4,3))
b = np.random.randint(1,11,size=(4,3))
print(a)
print('\n')
print(b)


[[8 6 8]
 [1 8 4]
 [1 8 4]
 [6 8 4]]


[[3 9 3]
 [9 2 2]
 [2 6 3]
 [9 4 1]]


In [109]:
40. # Perform a dot product on the two newest arrays you created

x=np.dot(a,b.T)
x

array([[102, 100,  76, 104],
       [ 87,  33,  62,  45],
       [ 87,  33,  62,  45],
       [102,  78,  72,  90]])

In [110]:
41. #( Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
print(a)
print(b.T)
print(np.dot(a,b.T))

[[8 6 8]
 [1 8 4]
 [1 8 4]
 [6 8 4]]
[[3 9 2 9]
 [9 2 6 4]
 [3 2 3 1]]
[[102 100  76 104]
 [ 87  33  62  45]
 [ 87  33  62  45]
 [102  78  72  90]]


In [10]:

import orbit
print("Orbit modules: ", dir(orbit.utilities))
     



Orbit modules:  ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'calc_year']


In [116]:
42. #Create two arrays of random integers between 0 & 10 of the same shape and save them to variables

a = np.random.randint(0,10,size=(3,3))
b = np.random.randint(0,10,size=(3,3))
print(a)
print(b)

[[9 5 0]
 [3 9 5]
 [5 4 0]]
[[7 4 4]
 [6 3 5]
 [3 2 6]]


In [118]:
43. # Find which elements of the first array are greater than 7

print(a)
print(b)
print(a[a>7])

[[9 5 0]
 [3 9 5]
 [5 4 0]]
[[7 4 4]
 [6 3 5]
 [3 2 6]]
[9 9]


In [124]:
44. # Which parts of each array are equal? (try using '==')

print([a==b])


[array([[False, False, False],
       [False, False,  True],
       [False, False, False]])]


In [125]:
45. # Sort one of the arrays you just created in ascending order

print(np.sort(a))

[[0 5 9]
 [3 5 9]
 [0 4 5]]


In [127]:
46. # Find the index with the maximum value in one of the arrays you've created

print(a)
print(np.argmax(a))

[[9 5 0]
 [3 9 5]
 [5 4 0]]
0


In [128]:
47. # Find the index with the minimum value in one of the arrays you've created

print(a)
print(np.argmin(a))

[[9 5 0]
 [3 9 5]
 [5 4 0]]
2


In [129]:
48. # Find the indexes with the maximum values down the 1st axis (axis=1) of one of the arrays you created

print(np.argmin(a, axis=1))

[2 0 2]


In [130]:
49. # Find the indexes with the minimum values across the 0th axis (axis=0) of one of the arrays you created

print(np.argmin(a, axis=0))

[1 2 0]


In [131]:
50. # Create an array with 10 evenly spaced numbers between 1 and 100

print(np.arange(0,100,10))

[ 0 10 20 30 40 50 60 70 80 90]
